# 1.数据集
## 1.1 Torchvision 包括的数据集
* MNIST
* COCO
* LSUN Classification
* ImageFolder
* Imagenet-12
* CIFAR10 and CIFAR100
* STL10
* SVHN
* Photo Tour

## 1.2 MNIST 介绍

In [ ]:
dset.MNIST(root, train = True, transform = None, target_transform = None, download = False)

## 1.3 加载数据

In [ ]:
torch.utils.data.DataLoader(dataset, batch_size = 1, shuffle = False, sampler = None, num_workers = 0, collate_fn = <function default_collate>, pin_memory = False, drop_last = False)

## 1.4 torchvision.models 模块包含预训练模型结构
* AlexNet
* VGG
* ResNet
* SqueezeNet
* DenseNet

### 调用构造函数构造随机权重的模型

In [6]:
    import torchvision.models as models
    resnet18 = models.resnet18()
    alexnet = models.alexnet()
    squeezenet = models.squeezenet1_0()
#     densenet = models.densenet_161()

### 构建预训练模型

In [ ]:
    import torchvision.models as models
    resnet18 = models.resnet18(pretrained = True)
    torchvisoin.models.alexnet(pretrained = False, ** kwargs)

## 1.5 定义神经网络模型

In [ ]:
from torch import autograd 
import torch.nn as nn
import torch.nn.functional as F
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
       x = F.relu(self.conv1(x))
       return F.relu(self.conv2(x))

# 2. 卷积层
## 2.1 一维卷积
    class torch.nn.Conv1d(in_channels, out_channels, kernel_size, stride = 1, padding = 0, dilation = 1, groups = 1, bias = True)

In [ ]:
m = nn.Conv1d(16, 33, 3, stride=2)
inputs = autograd.Variable(torch.randn(20, 16, 50))
output = m(inputs)
print(output)

## 2.2 池化层
    class torch.nn.MaxPool1d(kernel_size, stride = None, padding =  0, dilation = 1, return_indices = False, ceil_mode = False)

In [ ]:
m = nn.MaxPool1d(3, stride=2)
input = autograd.Variable(torch.randn(20, 16, 50))
output = m(input)
print(output)

## 2.3 小型ConvNet

In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
class MNISTConvNet(nn.Module):
    def __init__(self):
        super(MNISTConvNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, 5)
        self.pool1 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(10, 20, 5)
        self.pool2 = nn.MaxPool2d(2, 2)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
    def forward(self, input):
        x = self.pool1(F.relu(self.conv1(input)))
        x = self.pool2(F.relu(self.conv2(x)))
        return x
net = MNISTConvNet()
print(net)
input = Variable(torch.randn(1, 1, 28, 28))
out = net(input)
print(out.size())

# 3. Functional 函数
## 3.1 torch.nn.functional 包里提供的函数
* convolution 函数
* Pooling
* 非线性激活函数
* Normalization 函数
* 线性函数
* Dropout 函数
* 距离函数( Distance Functions )
* 损失函数( Loss Function )
* vision functions

## 3.2 torch.nn.functional.conv1d
    torch.nn.functional.conv1d(input, weight, bias = None, stride = 1, padding = 0, dilation = 1, groups = 1)

In [21]:
from torch import autograd as autograd
filters = autograd.Variable(torch.randn(1, 1, 3))
inputs = autograd.Variable(torch.randn(2, 1, 3))
print(filters)
print(inputs)
F.conv1d(inputs, filters)

tensor([[[-0.8862, -1.5707,  0.4922]]])
tensor([[[ 1.3507,  0.7947,  0.8037]],

        [[ 0.9339,  0.9322, -1.1509]]])


tensor([[[-2.0495]],

        [[-2.8583]]])

## 3.3 Pooling
### 3.3.1 常见 Pooling
* Mean-Pooling
* Max-Pooling
* Stochastic-Pooling

### 3.3.2 torch.nn.functional.avg_pool1d
    torch.nn.functional.avg_pool1d (input, kernel_size, stride = None, padding = 0, ceil_mode = False, count_include_pad = True)

## 3.4 激活函数
### 3.4.1 sigmoid 函数
    torch.nn.functional.sigmoid(input)
    
$$ f(x)= \frac{1}{1 + e^{-x}} $$

    m = nn.sigmoid()

### 3.4.2 Tanh 函数
    torch.nn.functional.tanh(input)
$$ tanh(x) = \frac{1 - e^{-2x}}{1 + e^{-2x}} $$

    m = nn.tanh()

### 3.4.3 ReLU 函数
    torch.nn.functional.relu(input, inplace = False)

$$ y= \begin{cases} 0, & x \leq 0 \\ x, & x > 0 \end{cases} $$

    m = nn.ReLU()

## 3.5 Dropout 函数
### 常见的Dropout 函数

In [ ]:
torch.nn.functional.dropout(input, p = 0.5, training = False, inplace = False)
torch.nn.functional.alpha_dropout(input, p = 0.5, training = False)
torch.nn.functional.dropout2d(input, p = 0.5, trainng = False, inplace = False)
torch.nn.functional.dropout3d(input, p = 0.5, trainging = False, inplace = False)

## 3.6 损失函数（Loss functions）
* 经验风险损失函数
* 结构风险损失函数
### 常见损失函数

In [ ]:
torch.nn.functional.kl_div(input, target, size_average=True)
torch.nn.functional.poisson_nll_loss(input, target, log_input=Ture, full=False, size_average=True)
torch.nn.functional.nll_loss(input, target, weight=None, size_average=True)
torch.nn.functional.cosine_embedding_loss(input, input2, target, margin = 0, size_average=True)

## 3.7 优化算法

In [ ]:
# optimizer = optim.SGD(model.parameters(), lr = 0.01, momentum = 0.9)
optimizer = optim.SGD(params, lr, momentum = 0, dampending = 0, weight_decay = 0, nesterov = False)
optimizer = optim.Adam([var1, var2], lr = 0.0001)

### 3.7.1 指定每一层学习速率

In [ ]:
optim.SGD([
          {'params': model.base.parameters()},
          {'params': model.classifier.parameters(), 'lr': 1e-3}
          ],lr = 1e-2, momentum = 0.9)

### 3.7.2 更新参数
* optimizer.step()

In [ ]:
for input, target in dataset:
    optimizer.zero_grad()
    output = model(input)
    loss = loss_fn(output, target)
    loss.backward()
    optimizer.step()

* 一些优化算法如 Conjugate Gradient 和 LBFGS 需要重复多次计算函数

In [ ]:
for input, target in dataset:
    def closure():
        optimizer.zero_grad()
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        return loss
    optimizer.step(closure)

## 3.8 自动求导机制
### 3.8.1 requires_grad

In [26]:
from torch.autograd import Variable as Variable
x = Variable(torch.randn(5,5))
y = Variable(torch.randn(5,5))
z = Variable(torch.randn(5,5), requires_grad= True)
a = x+y
print(a.requires_grad)
b = a+z
print(b.requires_grad)

False
True


### 冻结训练好的模型参数

In [ ]:
model = torchvision.models.resnet18(pretrained = True)
for param in model.parameters():
    param.requires_grad = False
model.fc = nn.Linear(512,100)
optimizer = optim.SGD(model.fc.parameters(), lr = 1e-2, momentum = 0.9)

### 3.8.2 volatile

In [ ]:
regular_input = Variable(torch.randn(5,5))
volatile_input = Variable(torch.randn(5,5), volatile = True)
model = torchvision.models.resnet18(pretrained = True)
model(regular_input).requires_grad
# True
model(volatile_input).requirs_grad
# False
model(volatile_input).volatile
# True
model(volatile_input).creator is None
# True

### 3.9 保存和加载模型
* 只保存和加载模型参数

In [ ]:
torch.save(the_model.state_dict(),PATH)
the_model = TheModelClass(* args, ** kwargs)
the_model.load_state_dict(torch.load(PATH))

* 保存和加载整个模型

In [ ]:
torch.save(the_model, PATH)
the_model = torch.load(PATH)

### 3.10 GPU加速运算

In [ ]:
Torch.cuda.current_device()
torch.cuda.device(idx)
x = torch.cuda.FloatTensor(1)
y = torch.FloatTensor(1)